$schema: https://azuremlschemas.azureedge.net/latest/schedule.schema.json
name: cron_with_settings_job_schedule
display_name: Simple cron job schedule
description: a simple daily cron job schedule

trigger:
  type: cron
  expression: "0 6 * * *"
  #start_time: "2022-07-10T10:00:00" # optional - default will be schedule creation time
  #time_zone: "Pacific Standard Time" # optional - default will be UTC

create_job: ofgemrunid