variables:
- template: ../config-infra-dev.yml

trigger:
- none

pool: $(ap_vm_image)
stages:
- stage: DeployTrainingPipeline
  displayName: Deploy Training Pipeline
  jobs:
    - job: DeployTrainingPipeline
      timeoutInMinutes: 120 # how long to run the job before automatically cancelling
      steps:
        - task: AzureCLI@2
          displayName: Connect to AML Workspace using CLI v2
          inputs:
            azureSubscription: $(ado_service_connection_aml_ws)
            scriptType: bash
            scriptLocation: inlineScript
            inlineScript: |
              az storage account keys list  --resource-group $(resource_group) --account-name $(storage_account)