variables:
- ${{ if eq(variables['Build.SourceBranchName'], 'release') }}:
    # 'main' branch: PRD environment
    - template: ../config-infra-prod.yml
- ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
    # 'main' branch: UAT environment
    - template: ../config-infra-prod.yml
- ${{ if and(ne(variables['Build.SourceBranchName'], 'main'),ne(variables['Build.SourceBranchName'], 'release')) }}:  
    # 'develop' or feature branches: DEV environment
    - template: ../config-infra-uat.yml

trigger:
- none

pool: $(ap_vm_image)

resources:
  pipelines:
    - pipeline: Promote
      source: Promote
      trigger: true

stages:
  - stage: GetArtifact
    jobs:
      - job: Build
        steps:
          - template: templates/install-az-cli.yml
          - template: templates/install-aml-cli.yml
          - task: DownloadBuildArtifacts@1
            displayName: "Download Artifact"
            inputs:
              buildType: specific
              project: data-science-platform
              pipeline: Promote
              specificBuildWithTriggering: true
              artifactName: model
              downloadPath: ./model
          - script: cat ./model/model/pipeline.env
          - script: rm ./model/model/pipeline.env
          - template: templates/promote-model.yml
            parameters:
              model_name: $(model_name)
              path: ./model/model/$(model_name)/$(model_name)
              workspace_name: $(ml_workspace)
              version: $(version)
              resource_group: $(resource_group)